# Generated by Django 2.1.4 on 2020-11-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=32)),
                ('middlename', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
