# Generated by Django 2.1.4 on 2020-11-14 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('departments', '0001_initial'),
        ('billings', '0001_initial'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.Faculties')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subjects')),
            ],
            options={
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='SectionsEnrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billings.Billings')),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.Enrollment')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.Sections')),
            ],
            options={
                'db_table': 'sect_enroll',
            },
        ),
    ]
