# Generated by Django 2.1.4 on 2020-11-14 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '__first__'),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissions',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.Courses'),
        ),
        migrations.AddField(
            model_name='admissions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='admissions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
