# Generated by Django 2.1.4 on 2020-11-14 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Courses')),
            ],
            options={
                'db_table': 'subj_courses',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('units', models.IntegerField()),
                ('recom_seme_taken', models.IntegerField()),
                ('recom_year_taken', models.IntegerField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.Departments')),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.AddField(
            model_name='subjcourses',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subjects'),
        ),
    ]
