# Generated by Django 2.1.4 on 2020-11-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_alias', models.CharField(blank=True, max_length=6, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('program_type', models.CharField(blank=True, choices=[('BS', 'Bachelor of Science'), ('AB', 'Arts Literature')], default='BS', max_length=2)),
                ('program_year', models.IntegerField(blank=True, null=True)),
                ('total_units', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_alias', models.CharField(blank=True, max_length=6, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=32, null=True)),
                ('middlename', models.CharField(blank=True, max_length=32, null=True)),
                ('lastname', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], default=None, max_length=1, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, choices=[('DEAN', 'Deparment Dean'), ('CHAIRP', 'Chairperson'), ('INST1', 'Instructor I'), ('INST2', 'Instructor II'), ('PROF1', 'Professor I'), ('PROF2', 'Professor II'), ('ASSOC', 'Associate Professor')], max_length=8, null=True)),
                ('date_hired', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.Departments')),
            ],
            options={
                'db_table': 'faculties',
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.Departments'),
        ),
    ]
